
version: "3.7"

networks:
  fabric:

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=fabriccadb
      - POSTGRES_USER=fabriccauser
      - POSTGRES_PASSWORD=adminpw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fabric

  ca:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: ca.${DOMAIN_OF_ORGANIZATION}
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CLIENT=/etc/hyperledger/fabric-ca-client
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/etc/hyperledger/fabric-ca/tls-cert.pem
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca.${DOMAIN_OF_ORGANIZATION}
      - FABRIC_CA_SERVER_CSR_CN=ca.${DOMAIN_OF_ORGANIZATION}
      - FABRIC_CA_SERVER_CSR_HOSTS=ca.${DOMAIN_OF_ORGANIZATION},${HOST_IP_ADDRESS}
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca/tlsca/ca.${ORGANIZATION_NAME_LOWERCASE}-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca/tlsca/ca.${ORGANIZATION_NAME_LOWERCASE}-cert.pem
      - FABRIC_CA_SERVER_DEBUG=false
      - FABRIC_CA_SERVER_DB_TYPE=postgres
      - FABRIC_CA_SERVER_DB_DATASOURCE=host=postgres port=5432 dbname=fabriccadb user=fabriccauser password=adminpw sslmode=disable
      - FABRIC_CA_SERVER_CONFIG=/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw --port 7054 --cfg.identities.allowremove'
    volumes:
      - ./${ORGANIZATION_NAME_LOWERCASE}Ca/:/etc/hyperledger/fabric-ca:rw
      # - ./postgresql-42.6.0.jar:/usr/local/share/postgresql-jdbc.jar
      - ./fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml:rw
      - ./${ORGANIZATION_NAME_LOWERCASE}Ca/server:/etc/hyperledger/fabric-ca-server:rw
      - ./${ORGANIZATION_NAME_LOWERCASE}Ca/client:/etc/hyperledger/fabric-ca-client:rw
      - ./ca-identity:/etc/hyperledger/artifacts
    ports:
      - 7054:7054
    networks:
      - fabric
    depends_on:
      - postgres
  peer:
    container_name: peer1.${DOMAIN_OF_ORGANIZATION}
    image: hyperledger/fabric-peer:2.5.10
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.${DOMAIN_OF_ORGANIZATION}
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=${ORGANIZATION_NAME}MSP
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/users/Admin@peer1.${DOMAIN_OF_ORGANIZATION}/msp
      - CORE_PEER_ADDRESS=peer1.${DOMAIN_OF_ORGANIZATION}:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.${DOMAIN_OF_ORGANIZATION}:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-fabric-idonate-network_fabric
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCH_DB_USERNAME}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCH_DB_PASSWORD}
      - FABRIC_CFG_PATH=/etc/hyperledger/peerConfig
      # Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/peers/peer1.${DOMAIN_OF_ORGANIZATION}/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/peers/peer1.${DOMAIN_OF_ORGANIZATION}/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/peers/peer1.${DOMAIN_OF_ORGANIZATION}/tls/ca.crt
    working_dir: /etc/hyperledger/peer
    command: peer node start
    ports:
      - 7051:7051
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/:/etc/hyperledger/peer:rw
      - ./config:/etc/hyperledger/configtx:rw
      - ./peer-config:/etc/hyperledger/peerConfig:rw
    depends_on:
      - orderer
      # - couchdb
    networks:
      - fabric

  peer2:
    container_name: peer2.${DOMAIN_OF_ORGANIZATION}
    image: hyperledger/fabric-peer:2.5.10
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer2.${DOMAIN_OF_ORGANIZATION}
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=${ORGANIZATION_NAME}MSP
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/users/Admin@peer2.${DOMAIN_OF_ORGANIZATION}/msp
      - CORE_PEER_ADDRESS=peer2.${DOMAIN_OF_ORGANIZATION}:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.${DOMAIN_OF_ORGANIZATION}:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-fabric-generic-network_fabric
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCH_DB_USERNAME}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCH_DB_PASSWORD}
      - FABRIC_CFG_PATH=/etc/hyperledger/peerConfig
      # Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/peers/peer2.${DOMAIN_OF_ORGANIZATION}/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/peers/peer2.${DOMAIN_OF_ORGANIZATION}/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/peers/peer2.${DOMAIN_OF_ORGANIZATION}/tls/ca.crt
    working_dir: /etc/hyperledger/peer
    command: peer node start
    ports:
      - 8051:8051
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/:/etc/hyperledger/peer:rw
      - ./config:/etc/hyperledger/configtx:rw
      - ./peer-config:/etc/hyperledger/peerConfig:rw
    depends_on:
      - orderer
      - couchdb
    networks:
      - fabric

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=${COUCH_DB_USERNAME}
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
    ports:
      - 5984:5984
    networks:
      - fabric

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.10
    tty: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.${DOMAIN_OF_ORGANIZATION}:7051
      - CORE_PEER_LOCALMSPID=${ORGANIZATION_NAME}MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/users/Admin@peer1.${DOMAIN_OF_ORGANIZATION}/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      # Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/peers/peer1.${DOMAIN_OF_ORGANIZATION}/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/peers/peer1.${DOMAIN_OF_ORGANIZATION}/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/peers/peer1.${DOMAIN_OF_ORGANIZATION}/tls/ca.crt
    working_dir: /etc/hyperledger
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/:/etc/hyperledger/crypto-config:rw
      - ./config:/etc/hyperledger/artifacts:rw
      - ./chaincode:/etc/hyperledger/chaincode:rw
    networks:
      - fabric
    depends_on:
      - orderer
      - peer
      - couchdb

  orderer:
    container_name: orderer1.${DOMAIN_OF_ORGANIZATION}
    image: hyperledger/fabric-orderer:2.5.10
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=${ORGANIZATION_NAME}OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
      - CORE_METRICS_PROVIDER=prometheus
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - export CORE_PEER_GOSSIP_BOOTSTRAP_TIMEOUT=10s
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/etc/hyperledger/orderer/tls/ca.crt
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=/etc/hyperledger/orderer/tls/ca.crt
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=/etc/hyperledger/orderer/tls/ca.crt
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/etc/hyperledger/orderer/tls/ca.crt
      - ORDERER_ADMIN_LISTENADDRESS=172.17.0.1:7053
    working_dir: /etc/hyperledger/
    command: orderer
    ports:
      - 7050:7050
      - 7053:7053
    volumes:
      - ./crypto-config/ordererOrganizations/orderers/orderer1.${DOMAIN_OF_ORGANIZATION}/:/etc/hyperledger/orderer:rw
    networks:
      - fabric

  orderer2:
    container_name: orderer2.${DOMAIN_OF_ORGANIZATION}
    image: hyperledger/fabric-orderer:2.5.10
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_LOCALMSPID=${ORGANIZATION_NAME}OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer2/msp
      - CORE_METRICS_PROVIDER=prometheus
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - export CORE_PEER_GOSSIP_BOOTSTRAP_TIMEOUT=10s
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer2/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer2/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/etc/hyperledger/orderer2/tls/ca.crt
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/orderer2/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/orderer2/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=/etc/hyperledger/orderer2/tls/ca.crt
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/etc/hyperledger/orderer2/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/etc/hyperledger/orderer2/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=/etc/hyperledger/orderer2/tls/ca.crt
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/etc/hyperledger/orderer2/tls/ca.crt
      - ORDERER_ADMIN_LISTENADDRESS=172.17.0.1:8053
    working_dir: /etc/hyperledger/
    command: orderer
    ports:
      - 8050:8050
      - 8053:8053
    volumes:
      - ./crypto-config/ordererOrganizations/orderers/orderer2.${DOMAIN_OF_ORGANIZATION}/:/etc/hyperledger/orderer2:rw
    networks:
      - fabric

  orderer3:
    container_name: orderer3.${DOMAIN_OF_ORGANIZATION}
    image: hyperledger/fabric-orderer:2.5.10
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_GENERAL_LOCALMSPID=${ORGANIZATION_NAME}OrdererMSP
      - CORE_METRICS_PROVIDER=prometheus
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer3/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - export CORE_PEER_GOSSIP_BOOTSTRAP_TIMEOUT=10s
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer3/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer3/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/etc/hyperledger/orderer3/tls/ca.crt
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/orderer3/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/orderer3/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=/etc/hyperledger/orderer3/tls/ca.crt
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/etc/hyperledger/orderer3/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/etc/hyperledger/orderer3/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=/etc/hyperledger/orderer3/tls/ca.crt
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/etc/hyperledger/orderer3/tls/ca.crt
      - ORDERER_ADMIN_LISTENADDRESS=172.17.0.1:9053
    working_dir: /etc/hyperledger/
    command: orderer
    ports:
      - 9050:9050
      - 9053:9053
    volumes:
      - ./crypto-config/ordererOrganizations/orderers/orderer3.${DOMAIN_OF_ORGANIZATION}/:/etc/hyperledger/orderer3:rw
    networks:
      - fabric
